"""ScamShield Web Command Center - final Flask frontend.

This is the FINAL frontend architecture (replacing the earlier Streamlit
prototype). It is a thin HTTP layer ONLY: every response comes from the real
`scamshield.analyze()` / `scamshield.analyze_chain()` calls. There is no
duplicated detection, scoring or chain logic here and none in the browser
(vanilla JS just renders whatever the API returns).

Security model (inherited from the engines, plus web-layer guards):
  * fully local - no external APIs, no DNS lookups, no URL fetching;
  * URLs are analysed statically - never opened, resolved or followed;
  * QR payloads are never executed - an uploaded image is written to a
    temporary file, analysed locally and the file is always deleted in a
    `finally` block;
  * UPI URIs are parsed statically - no payment is ever executed;
  * no database, no authentication, no cloud-dependent service - safe to host
    behind any WSGI server or platform that runs Python.

Deployment compatibility:
  * `python web/app.py`           -> dev server (host/port/debug from env)
  * `flask --app web.app run`     -> Flask dev server
  * gunicorn/webapp2/uWSGI        -> WSGI `application` = `web.app:app`
  * Production on Render: `gunicorn web.app:app` (the repo's
    gunicorn.conf.py binds to 0.0.0.0:$PORT, honouring Render's PORT).
  * Environment variables (safe defaults; DEBUG is NEVER on by default):
        HOST | SCAMSHIELD_HOST     (default 127.0.0.1 for the dev server)
        PORT | SCAMSHIELD_PORT     (default 5000; Render injects PORT)
        DEBUG| SCAMSHIELD_DEBUG    (default 0; set '1' to enable dev debug)
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path

# Make the repo root and the src/ layout importable no matter where the app is
# run from (`python web/app.py`, `flask --app web.app`, a WSGI server, tests).
_WEB_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _WEB_DIR.parent
for _p in (_REPO_ROOT, _REPO_ROOT / "src"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from flask import Flask, jsonify, make_response, render_template, request  # noqa: E402

from scamshield import __version__ as SHIELD_VERSION  # noqa: E402
from scamshield import analyze, analyze_chain  # noqa: E402
from scamshield.ml.predict import (  # noqa: E402
    load_model as _ml_load_model,
    predict_message as _ml_predict_message,
)

ALLOWED_QR_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp"}
MAX_QR_UPLOAD_BYTES = 5 * 1024 * 1024  # 5 MiB

_RESEARCH_DIR = _REPO_ROOT / "models" / "research"


def _read_json(directory: Path, name: str):
    """Read one research artifact JSON safely; never fails, no network."""
    try:
        path = directory / name
        if not path.exists():
            return None
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _leakage_examples(leakage: dict) -> dict:
    examples = {"exact": [], "normalised": []}
    for kind in ("exact", "normalised"):
        table = (leakage.get(f"{kind}_overlap") or {}).items()
        for pair, items in table:
            for item in (items or [])[:3]:
                examples[kind].append({"pair": pair, "text": item})
            if len(examples[kind]) >= 6:
                break
    return examples


def load_research_payload() -> dict | None:
    """Compact real research values for the /research dashboard.

    Reads the artifacts generated by `python -m app.research_eval`. Returns
    None when the artifacts are absent so the UI can explain how to generate
    them instead of inventing numbers.
    """
    summary = _read_json(_RESEARCH_DIR, "evaluation_summary.json")
    if not summary:
        return None
    dp = summary.get("dataset_profile") or {}
    test = dp.get("test") or {}
    distribution = test.get("distribution") or {}

    fnfp_by_system = {}
    for key, system in (("rule_engine", "Rule Engine"), ("ml", "Local ML")):
        engine = summary.get(key) or {}
        fnfp_by_system[system] = {
            "fn_count": engine.get("fn_count"),
            "fp_count": engine.get("fp_count"),
        }

    comparison = []
    for row in (summary.get("comparison") or []):
        enriched = dict(row)
        extra = (fnfp_by_system or {}).get(enriched.get("system"))
        if extra:
            enriched.update(extra)
        comparison.append(enriched)

    leakage_report = _read_json(_RESEARCH_DIR, "leakage_report.json") or {}
    leakage_totals = leakage_report.get("totals") or {}
    leakage_clean = summary.get("leakage_clean_combined") or {}

    return {
        "timestamp": summary.get("timestamp"),
        "dataset": {
            "raw_counts": dp.get("raw_counts") or {},
            "splits": {
                "train": (dp.get("train") or {}).get("n"),
                "validation": (dp.get("validation") or {}).get("n"),
                "test": test.get("n"),
                "total": (dp.get("deduped_counts") or {}).get("total"),
            },
            "test": {
                "n": test.get("n"),
                "scam": distribution.get("scam"),
                "safe": distribution.get("safe"),
                "languages": test.get("languages") or {},
                "scam_categories": test.get("scam_categories") or {},
            },
        },
        "comparison": comparison,
        "leakage": {
            "exact_total": leakage_totals.get("exact"),
            "normalised_total": leakage_totals.get("normalised"),
            "overlap_type": leakage_report.get("overlap_type"),
            "affected_pairs": leakage_report.get("affected_split_pairs") or [],
            "recommendation": leakage_report.get("recommendation"),
            "examples": _leakage_examples(leakage_report),
            "clean_subset": leakage_clean.get("n_samples"),
            "clean_metrics": {
                k: leakage_clean.get(k)
                for k in ("accuracy", "precision", "recall", "f1")
            },
        },
        "latency": _read_json(_RESEARCH_DIR, "latency_results.json") or {},
        "limitations": summary.get("limitations") or [],
    }


_STATIC_ASSETS = ("style.css", "identity.css", "app.js")


def _static_asset_version(static_dir: Path) -> str:
    """Fingerprint the served CSS/JS bundle for cache-busting asset URLs.

    The digest changes whenever any served frontend asset changes, so browsers
    and CDNs cannot keep applying a stale stylesheet or script after a new
    deployment. Missing files never break the app; they are simply omitted.
    """
    digest = hashlib.sha1()
    for name in _STATIC_ASSETS:
        try:
            data = (static_dir / name).read_bytes()
        except OSError:
            continue
        digest.update(name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(data)
    return digest.hexdigest()[:12]


def _env_bool(name: str, default: str = "0") -> bool:
    return os.environ.get(name, default).strip().lower() in {"1", "true", "yes", "on"}


def ml_model_available() -> bool:
    """Whether the locally trained model file is present (never fetched)."""
    try:
        return _ml_load_model() is not None
    except Exception:
        return False


def _json_body() -> dict:
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        raise ValueError("Request body must be a JSON object.")
    return data


def _require_text(data: dict, field: str) -> str:
    value = data.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"'{field}' must be a non-empty string.")
    return value


def _error_response(status: int, error_type: str, error: str):
    return jsonify(
        {
            "success": False,
            "input_type": None,
            "status": "ERROR",
            "error_type": error_type,
            "error": error,
            "risk_score": 0,
            "risk_level": "LOW",
        }
    ), status


def create_app(**config_kwargs) -> Flask:
    app = Flask(
        __name__,
        template_folder=str(_WEB_DIR / "templates"),
        static_folder=str(_WEB_DIR / "static"),
    )
    app.config.update(config_kwargs)
    app.config.setdefault("MAX_CONTENT_LENGTH", MAX_QR_UPLOAD_BYTES + 1024)
    app.json.ensure_ascii = False
    app.json.sort_keys = False
    asset_version = _static_asset_version(Path(app.static_folder))

    # ------------------------------------------------------------------ /
    # Health + UI
    # ------------------------------------------------------------------ /

    @app.get("/")
    def index():
        # The dynamic shell is never cached: after each deployment it carries
        # fresh fingerprinted CSS/JS URLs, preventing stale production styling.
        response = make_response(render_template(
            "index.html",
            research_payload=load_research_payload(),
            asset_version=asset_version,
        ))
        response.headers["Cache-Control"] = "no-store"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
        return response

    @app.get("/api/health")
    def health():
        return jsonify(
            {
                "service": "scamshield-web",
                "status": "ok",
                "version": SHIELD_VERSION,
                "offline": True,
                "ml_model_available": ml_model_available(),
                "url_reputation": "static-only (never opened, never resolved)",
            }
        )

    # ------------------------------------------------------------------ /
    # Analyzer endpoints (thin wrappers over the REAL engines)
    # ------------------------------------------------------------------ /

    @app.post("/api/analyze/message")
    def api_message():
        try:
            data = _json_body()
            content = _require_text(data, "message")
        except ValueError as exc:
            return _error_response(400, "validation", str(exc))
        return jsonify(analyze("message", content))

    @app.post("/api/analyze/url")
    def api_url():
        try:
            data = _json_body()
            content = _require_text(data, "url")
        except ValueError as exc:
            return _error_response(400, "validation", str(exc))
        return jsonify(analyze("url", content))

    @app.post("/api/analyze/upi")
    def api_upi():
        try:
            data = _json_body()
            content = _require_text(data, "upi")
        except ValueError as exc:
            return _error_response(400, "validation", str(exc))
        return jsonify(analyze("upi", content))

    @app.post("/api/analyze/qr")
    def api_qr():
        upload = request.files.get("qr_image")
        if upload is None or not upload.filename:
            return _error_response(400, "validation",
                                   "A file field 'qr_image' is required.")
        suffix = Path(upload.filename).suffix.lower()
        if suffix not in ALLOWED_QR_EXTENSIONS:
            return _error_response(
                400, "validation",
                f"Unsupported image type '{suffix or 'none'}'. Allowed: "
                + ", ".join(sorted(ALLOWED_QR_EXTENSIONS)) + ".",
            )
        payload = upload.stream.read(MAX_QR_UPLOAD_BYTES + 1)
        if len(payload) > MAX_QR_UPLOAD_BYTES:
            return _error_response(
                413, "validation",
                f"Uploaded image exceeds the {MAX_QR_UPLOAD_BYTES // (1024 * 1024)} MiB limit.",
            )

        tmp_path = None
        try:
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                tmp.write(payload)
                tmp_path = tmp.name
            # Never execute QR content: the engine only decodes + analyses
            # statically; the temp file is removed in the finally block.
            return jsonify(analyze("qr", tmp_path))
        finally:
            if tmp_path is not None:
                try:
                    os.unlink(tmp_path)
                except OSError:
                    pass

    @app.post("/api/analyze/chain")
    def api_chain():
        try:
            data = _json_body()
            stages = data.get("stages")
            if not isinstance(stages, list):
                raise ValueError("'stages' must be a list of analyzed artifacts.")
        except ValueError as exc:
            return _error_response(400, "validation", str(exc))
        return jsonify(analyze("chain", stages))

    @app.post("/api/analyze/link-change")
    def api_link_change():
        """Link Purifier / Link Safety Monitor (static, offline).

        Body shapes:
            {"url": "..."}                            -> purify/inspect one link
            {"baseline_url": "...", "current_url": "..."} -> compare two versions
        The URL is NEVER opened, resolved or followed; only its structure is
        inspected/reused through the existing URL Intelligence engine.
        """
        try:
            data = _json_body()
        except ValueError as exc:
            return _error_response(400, "validation", str(exc))
        result = analyze("link_change", data)
        if not result.get("success") and result.get("status") == "ERROR" \
                and result.get("error_type") == "validation":
            return _error_response(400, "validation",
                                   result.get("error") or "Invalid link-change input.")
        return jsonify(result)

    # ---------------------------------------------------------------- /
    # Global error handling
    # ---------------------------------------------------------------- /

    @app.errorhandler(404)
    def not_found(_err):
        return _error_response(404, "not_found", "Endpoint not found.")

    @app.errorhandler(405)
    def method_not_allowed(_err):
        return _error_response(405, "method_not_allowed", "Method not allowed.")

    @app.errorhandler(413)
    def payload_too_large(_err):
        return _error_response(413, "validation", "Request payload too large.")

    @app.errorhandler(500)
    def internal_error(_err):
        app.logger.exception("Unexpected error while serving request")
        return _error_response(500, "internal",
                               "Internal analysis error.")

    return app


# Module-level WSGI application object (`web.app:app`).
app = create_app()


def main() -> None:
    # Generic HOST / PORT / DEBUG are honoured first (Render injects PORT),
    # with the SCAMSHIELD_* names kept as backwards-compatible aliases.
    # Dev-server defaults stay localhost-bound; production (gunicorn) uses
    # gunicorn.conf.py which defaults to 0.0.0.0 for container/cloud hosts.
    host = os.environ.get("HOST") or os.environ.get("SCAMSHIELD_HOST") or "127.0.0.1"
    try:
        port = int(os.environ.get("PORT") or os.environ.get("SCAMSHIELD_PORT") or "5000")
    except ValueError:
        port = 5000
    debug = _env_bool("DEBUG") or _env_bool("SCAMSHIELD_DEBUG")
    print(f"ScamShield Web {SHIELD_VERSION} - "
          f"http://{host}:{port} (offline, static-only analysis)")
    app.run(host=host, port=port, debug=debug)


if __name__ == "__main__":
    main()